server:
   port: 8081
spring:
  rabbitmq:
    #ip
    host: 18.166.225.206
    #端口
    port: 5672
    username: cloud
    password: 12345678
    #虚拟机
    virtual-host: /
    connection-timeout: 15000
    publisher-confirm-type: correlated
    #回退消息
    publisher-returns: true
